name = "secrets-test"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables go here
# EXAMPLE_VAR = "example_value"

# Uncomment and configure if using KV storage
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Uncomment and configure if using D1 database
# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"

# Uncomment and configure if using R2 storage
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
# preview_bucket_name = "my-preview-bucket"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   "example.com/*",
#   "www.example.com/*"
# ]
